<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'Acerca de',
    'Are you sure you want to delete this item?' => 'Esta seguro de borrar este item',
    'Congratulations!' => 'Felicitaciones',
    'Contact' => 'Contacto',
    'Create' => 'Crear',
    'Create Status' => 'Crear estado',
    'Created At' => 'Creado a las',
    'Delete' => 'Borrar',
    'Get started with Yii' => '',
    'Heading' => '',
    'Home' => 'Inicio',
    'ID' => '',
    'Logout' => 'Cerrar sesión',
    'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.' => '',
    'Message' => 'Mensaje',
    'My Company' => 'Mi compañia',
    'Permissions' => '',
    'Reset' => '',
    'Search' => 'Buscar',
    'Sign In' => 'Registrarse',
    'Sign Up' => 'Iniciar sesión',
    'Status' => 'Estado',
    'Statuses' => 'Estados',
    'Update' => 'Actualizar',
    'Update {modelClass}: ' => 'Actualizar {modelClass}: ',
    'Updated At' => 'Actualizo a las',
    'Yii Documentation' => 'Documentacion Yii',
    'You have successfully created your Yii-powered application.' => '',
];
